vision:
  camera_index: 0
  fps: 20
  image_width: 640
  image_height: 480
  focal_length_mm: 3.04
  pixel_size_mm: 0.00112
  marker_size_mm: 50
mavlink_communication:
  device_string : "/dev/ttyUSB0"
  refresh_rate_s: 0.05
