from fastapi import APIRouter, WebSocket
from src.configuration.service_locator import ServiceLocator

from src.application.communication.antenna_communication_thread import AntennaCommunicationThread
