name: Python Formatter

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r dev-requirements.txt

    - name: Check if ./src exists
      id: bot_exists
      run: echo ::set-output name=exists::$(test -d ./src && echo "true" || echo "false")

    - name: Check code with ruff for ./src
      if: steps.bot_exists.outputs.exists == 'true'
      run: |
        ruff check ./src

    - name: Check code with black for ./src
      if: steps.bot_exists.outputs.exists == 'true'
      run: |
        black ./src
